// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZoaIdsBackend.Data;

#nullable disable

namespace ZoaIdsBackend.Migrations
{
    [DbContext(typeof(ZoaIdsContext))]
    partial class ZoaIdsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZoaIdsBackend.Common.ApplicationJobRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Caller")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CompletedJobs");
                });

            modelBuilder.Entity("ZoaIdsBackend.Modules.AircraftTypes.Models.AircraftType", b =>
                {
                    b.Property<int>("AircraftTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AircraftTypeId"));

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConslidatedWakeTurbulenceCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EngineCount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FaaEngineNumberType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FaaWeightClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IcaoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IcaoWakeTurbulenceCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LandAndHoldShortGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SameRunwaySeparationCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AircraftTypeId");

                    b.ToTable("AircraftTypes");
                });

            modelBuilder.Entity("ZoaIdsBackend.Modules.Airlines.Models.Airline", b =>
                {
                    b.Property<string>("IcaoId")
                        .HasColumnType("text");

                    b.Property<string>("Callsign")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IcaoId");

                    b.ToTable("Airlines");
                });

            modelBuilder.Entity("ZoaIdsBackend.Modules.DigitalAtis.Models.Atis", b =>
                {
                    b.Property<string>("IcaoId")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("Altimeter")
                        .HasColumnType("integer");

                    b.Property<char>("InfoLetter")
                        .HasColumnType("character(1)");

                    b.Property<DateTime>("IssueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WeatherText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IcaoId", "Type");

                    b.ToTable("Atises");
                });

            modelBuilder.Entity("ZoaIdsBackend.Modules.NasrData.Models.Airport", b =>
                {
                    b.Property<string>("FaaId")
                        .HasColumnType("text");

                    b.Property<string>("Artcc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Elevation")
                        .HasColumnType("double precision");

                    b.Property<string>("IcaoId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TrueToMagneticDelta")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("FaaId");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("ZoaIdsBackend.Modules.RunwayVisualRange.Models.RvrObservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AirportFaaId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CenterlineLightSetting")
                        .HasColumnType("integer");

                    b.Property<int?>("EdgeLightSetting")
                        .HasColumnType("integer");

                    b.Property<int?>("Midpoint")
                        .HasColumnType("integer");

                    b.Property<int?>("MidpointTrend")
                        .HasColumnType("integer");

                    b.Property<int?>("Rollout")
                        .HasColumnType("integer");

                    b.Property<int?>("RolloutTrend")
                        .HasColumnType("integer");

                    b.Property<string>("RunwayEndName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Touchdown")
                        .HasColumnType("integer");

                    b.Property<int?>("TouchdownTrend")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RvrObservations");
                });

            modelBuilder.Entity("ZoaIdsBackend.Modules.VatsimData.Models.Artcc", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("IsOceanic")
                        .HasColumnType("boolean");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<string>("SerializedBoundingPolygons")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.ToTable("Artccs");
                });

            modelBuilder.Entity("ZoaIdsBackend.Modules.VatsimData.Models.VatsimSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("VatsimSnapshots");
                });

            modelBuilder.Entity("ZoaIdsBackend.Modules.Weather.Models.Metar", b =>
                {
                    b.Property<string>("StationId")
                        .HasColumnType("text");

                    b.Property<float?>("AltimeterInHg")
                        .HasColumnType("real");

                    b.Property<float?>("DewPointC")
                        .HasColumnType("real");

                    b.Property<DateTime>("ObservationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float?>("SeaLevelPressureMb")
                        .HasColumnType("real");

                    b.Property<float?>("TempC")
                        .HasColumnType("real");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int?>("VerticalVisibilityFt")
                        .HasColumnType("integer");

                    b.Property<float?>("VisibilityMi")
                        .HasColumnType("real");

                    b.Property<string>("WeatherString")
                        .HasColumnType("text");

                    b.HasKey("StationId");

                    b.ToTable("Metars");
                });

            modelBuilder.Entity("ZoaIdsBackend.Modules.NasrData.Models.Airport", b =>
                {
                    b.OwnsOne("ZoaIdsBackend.Common.GeoCoordinate", "Location", b1 =>
                        {
                            b1.Property<string>("AirportFaaId")
                                .HasColumnType("text");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision");

                            b1.HasKey("AirportFaaId");

                            b1.ToTable("Airports");

                            b1.WithOwner()
                                .HasForeignKey("AirportFaaId");
                        });

                    b.OwnsMany("ZoaIdsBackend.Modules.NasrData.Models.Runway", "Runways", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("AirportFaaId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Length")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("AirportFaaId");

                            b1.ToTable("Runway");

                            b1.WithOwner()
                                .HasForeignKey("AirportFaaId");

                            b1.OwnsMany("ZoaIdsBackend.Modules.NasrData.Models.Runway+End", "Ends", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("AirportFaaId")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<double?>("EndElevation")
                                        .HasColumnType("double precision");

                                    b2.Property<int>("MagneticHeading")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("RunwayName")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<int>("RunwayOwnerId")
                                        .HasColumnType("integer");

                                    b2.Property<double?>("TdzElevation")
                                        .HasColumnType("double precision");

                                    b2.Property<int?>("TrueHeading")
                                        .HasColumnType("integer");

                                    b2.HasKey("Id");

                                    b2.HasIndex("RunwayOwnerId");

                                    b2.ToTable("End");

                                    b2.WithOwner()
                                        .HasForeignKey("RunwayOwnerId");
                                });

                            b1.Navigation("Ends");
                        });

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Runways");
                });

            modelBuilder.Entity("ZoaIdsBackend.Modules.Weather.Models.Metar", b =>
                {
                    b.OwnsOne("ZoaIdsBackend.Common.GeoCoordinate", "Location", b1 =>
                        {
                            b1.Property<string>("MetarStationId")
                                .HasColumnType("text");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision");

                            b1.HasKey("MetarStationId");

                            b1.ToTable("Metars");

                            b1.WithOwner()
                                .HasForeignKey("MetarStationId");
                        });

                    b.OwnsOne("ZoaIdsBackend.Modules.Weather.Models.WindObservation", "Wind", b1 =>
                        {
                            b1.Property<string>("MetarStationId")
                                .HasColumnType("text");

                            b1.Property<int>("DirectionTrueDegrees")
                                .HasColumnType("integer");

                            b1.Property<int?>("GustKnots")
                                .HasColumnType("integer");

                            b1.Property<int>("SpeedKnots")
                                .HasColumnType("integer");

                            b1.HasKey("MetarStationId");

                            b1.ToTable("Metars");

                            b1.WithOwner()
                                .HasForeignKey("MetarStationId");
                        });

                    b.OwnsMany("ZoaIdsBackend.Modules.Weather.Models.SkyCoverObservation", "SkyCovers", b1 =>
                        {
                            b1.Property<int>("SkyCoverId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("SkyCoverId"));

                            b1.Property<int?>("BaseFtAgl")
                                .HasColumnType("integer");

                            b1.Property<string>("StationId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.HasKey("SkyCoverId");

                            b1.HasIndex("StationId");

                            b1.ToTable("SkyCoverObservation");

                            b1.WithOwner()
                                .HasForeignKey("StationId");
                        });

                    b.Navigation("Location");

                    b.Navigation("SkyCovers");

                    b.Navigation("Wind");
                });
#pragma warning restore 612, 618
        }
    }
}
